repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8

-   repo: https://github.com/pycqa/pylint
    rev: v2.13.5
    hooks:
    - id: pylint

-   repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
    - id: bandit
