default_language_version:
    python: python3.10

repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      args: ["--profile", "black"]

-   repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: "./scripts/run_mypy"
      language: system
      types: [python]
      require_serial: true
      verbose: true
