name: Main

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    branches:
      - 'main'

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          ./scripts/setup_dev.sh
      - name: Run pre-commit
        run: |
          SKIP=mypy pre-commit run
      - name: Run mypy
        run: |
          pre-commit run mypy -a
      - name: Test with pytest
        env:
          TEST_AZURE_CONN_STRING: ${{ secrets.TEST_AZURE_CONN_STRING }}
          TEST_GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.TEST_GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          pytest tests

  publish:
    needs: test
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install build pex
      - name: Build package
        run: python -m build
      - name: Build pex
        run: pex -f ./dist -c renameit -o renameit.pex renameit
      - name: Create github release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.whl
            renameit.pex
      - name: Publish package (test pypi)
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: hasanj
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: hasanj/renameit:${{github.ref_name}}
          file: ./Dockerfile.release
